<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>bd865ac9-8da1-4565-8939-ed65d64c8661</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.101.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	  <PackageReference Include="DotNetEnv" Version="3.2.0" />
	  <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
	  <PackageReference Include="Hangfire.AspNetCore" Version="1.8.24" />
	  <PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
	  <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.9" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
	  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
	  <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
	  <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
	  <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.15.0" />
	  <PackageReference Include="MailKit" Version="4.17.0" />
	  <PackageReference Include="QuestPDF" Version="2026.7.1" />
	  <PackageReference Include="RazorLight" Version="2.3.1" />
  </ItemGroup>

</Project>
